### ISSUE TITLE
Bug: massive edit issues clear tags

### ISSUE THREAD

**Issue by pbielinski** [AlphaNodes/additional_tags#10]
Steps to reproduce:
1. Select (on issue list) two or more issues
2. Bulk edit some values (or none)
3. Save bulk edit

Result: all tags will be removed from tickets
Expected result: tags will not be removed (only added new one)

**Comment by alexandermeindl** [comment]
Hi @pbielinski 
thanks for reporting this! I fixed this problem with my last commit.

Please let me know, if this is working for you, too.

**Comment by pbielinski** [comment]
Hi @alexandermeindl 

thanks :) works perfectly
