### ISSUE TITLE
additional_tags 1.0.0 incompatible with additionals 3.0.1

### ISSUE THREAD

**Issue by GaryAitken** [AlphaNodes/additional_tags#11]
I have redmine 4.1.1 installed with additionals plugin 3.0.1.  When I installed the additional_tags plugin, I got an error for an undefined method "additionals_settings_select".  Sure enough, it is missing from the additionals plugin helper, in plugins/additionals/app/helpers/additionals_settings_helper.rb.

If I go to a temp directory and clone additionals:

```
cd ~/tmp
mkdir additionals
git clone https://www.github.com/alphanodes/additionals.git

```
I get an up-to-date copy which includes the missing method.
This is on branch origin/master.

When I cd'd to the redmine/plugins/additionals directory and did a git pull, it updated but the files are different, and the method is still missing.
 
```
$ git status
On branch stable
Your branch is up to date with 'origin/stable'.
```

The clone is on branch master, so apparently the stable branch is missing the needed methods.

**Comment by alexandermeindl** [comment]
Hi @GaryAitken 

at the moment you have the following options:

1) use stable additionals version with additional_tags 1.0.0

```
git clone https://www.github.com/alphanodes/additionals.git
git clone https://www.github.com/alphanodes/additional_tags.git
```

2) use latest additionals version with latest additional_tags

```
git clone -b stable https://www.github.com/alphanodes/additionals.git
git clone -b 1.0.0 https://www.github.com/alphanodes/additional_tags.git
```

**Comment by GaryAitken** [comment]
Thanks, I upgraded additionals and that solved the problem.  It would be nice if the installation instructions indicated #1 as possibly a preferred method, given that some users might not like installing a development version in a production environment.

**Comment by alexandermeindl** [comment]
Hi @GaryAitken 
I updated the installation instruction for stable version.

**Comment by GaryAitken** [comment]
Much appreciated
For those not super familiar with the rails environment, aren't the bundle install and bundle exec supposed to be executed from the top level directory?  So clearer instructions might say:
  cd redmine
  bundle install
  bundel exec ...
Similar to the step 1 instructions?
Otherwise, one might execute them from the plugins directory.
Maybe it doesn't matter; I don't know.

**Comment by alexandermeindl** [comment]
Hi @GaryAitken 

thanks for your review! You are right, this needed an update. I updated it and hope its better now.

**Comment by GaryAitken** [comment]
It doesn't look updated to me.  I see this:
```
2. Install dependencies and migrate database.
bundle install
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```
That is incorrect.
It should be something like:
```
cd additional_tags
bundle install
cd $REDMINE_ROOT
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```
At least I think that's correct.

**Comment by alexandermeindl** [comment]
I changed step 1. Now a directory change is not required anymore. I find it a better solution, then changing directory with each step. What do you think?

**Comment by GaryAitken** [comment]
I see how you changed step one.  Unfortunately, I don't know if a "bundle install" from $REDMINE_ROOT will install the gems needed by the plugins.  I have not tried it, and i don't understand the ruby load process.  
If I do: 
```
  cd $REDMINE_ROOT/plugins/additional_tags/
  bundle list
```
and
```
  cd $REDMINE_ROOT
  bundle list
```
I see gems for additional_tags which are not present at the top level, and ones with different versions:
```
additional_tags:                 redmine:
  activemodel (6.0.3.6)          5.2.4.2
  activerecord (6.0.3.6)         5.2.4.2
  activesupport (6.0.3.6)        5.2.4.2
  acts-as-taggable-on (6.5.0)
  additional_tags (1.0.0)       
  concurrent-ruby (1.1.8)        1.1.7
  i18n (1.8.10)
  minitest (5.14.4)              5.14.2
  thread_safe (0.3.6)
  tzinfo (1.2.9)                 1.2.8
  zeitwerk (2.4.2)               not present
```
As long as you're confident that it works, that's fine.

**Comment by alexandermeindl** [comment]
Hi @GaryAitken 

you should run bundle always in REDMINE_ROOT, never in plugin directory => this should work.

**Comment by alexandermeindl** [comment]
It think this is can be closed. Feel free to reopen it, if there are more problems with it.
