### ISSUE TITLE
delete tag error in redmine 4.2.1

### ISSUE THREAD

**Issue by wickyhu** [AlphaNodes/additional_tags#12]
Hi,

I installed the stable version with redmine 4.2.1.

When I tried to delete a tag without issue attached, I got "page not found" and below error in production log: 
![image](https://user-images.githubusercontent.com/2106893/118425110-0a40d680-b6fb-11eb-86e4-dd62573c0c51.png)
![image](https://user-images.githubusercontent.com/2106893/118425173-32303a00-b6fb-11eb-901d-9588509194f7.png)

`
F, [2021-05-17T02:15:15.619173 #1] FATAL -- :   
F, [2021-05-17T02:15:15.619287 #1] FATAL -- : ActiveRecord::RecordNotFound (ActiveRecord::RecordNotFound):
F, [2021-05-17T02:15:15.619338 #1] FATAL -- :   
F, [2021-05-17T02:15:15.619375 #1] FATAL -- : plugins/additional_tags/app/controllers/additional_tags_controller.rb:72:in `bulk_find_tags'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:56:in `call'
F, [2021-05-17T02:24:58.983435 #1] FATAL -- :   
F, [2021-05-17T02:24:58.983519 #1] FATAL -- : ActiveRecord::RecordNotFound (ActiveRecord::RecordNotFound):
F, [2021-05-17T02:24:58.983556 #1] FATAL -- :   
F, [2021-05-17T02:24:58.983587 #1] FATAL -- : plugins/additional_tags/app/controllers/additional_tags_controller.rb:72:in `bulk_find_tags'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
`
Regards
Wicky

**Comment by alexandermeindl** [comment]
Hi @wickyhu 
thanks for reporting this! I fixed the problem with delete a tag without an existing relation with my last commit.

**Comment by wickyhu** [comment]
Hi,

I confirmed the issue was fixed after upgraded.

Thanks!
