### ISSUE TITLE
Redmine 500 error when activating Issue Tags

### ISSUE THREAD

**Issue by AID-PMBD** [AlphaNodes/additional_tags#17]
When activating Issue Tags I get a Redmine 500 error.

**Environment:**
  Redmine version                4.1.4.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
**SCM:**
  Git                            2.25.1
  Filesystem                     
**Redmine plugins:**
  additional_tags                1.0.0
  additionals                    3.0.3

**Log file content:**

```
Completed 500 Internal Server Error in 286ms (ActiveRecord: 173.3ms)

NameError (undefined local variable or method `initialize_tags_filter' for #<IssueQuery:0x000055810a6b60a8>
Did you mean?  initialize_ids_filter
               initialize_author_filter
               initialize_watcher_filter
               initialize_updated_filter
               initialize_created_filter):

plugins/additional_tags/lib/additional_tags/patches/issue_query_patch.rb:24:in `initialize_available_filters_with_tags'
app/models/query.rb:657:in `available_filters'
app/models/query.rb:696:in `type_for'
app/models/query.rb:447:in `block in validate_query_filters'
app/models/query.rb:445:in `each_key'
app/models/query.rb:445:in `validate_query_filters'
app/controllers/issues_controller.rb:48:in `index'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```

**Comment by alexandermeindl** [comment]
Hi @AID-PMBD,

please try latest version of additionals plugin with latest additional_tags version. If you want to stick to additional_tags version 1.0.0, you need to use additionals version 3.0.2.

**Comment by AID-PMBD** [comment]
Hello Alex,

Thank you for the quick reply!

I updated the Additional tags plugin to 1.0.1. My Environment now looks like this:

**Environment:**
  Redmine version                4.1.4.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
**SCM:**
  Git                            2.25.1
  Filesystem                     
**Redmine plugins:**
  additional_tags                1.0.1
  additionals                    3.0.3


**My log file says:**

```
Started GET "/projects/pmbd/issues" for 192.168.178.25 at 2021-09-20 16:51:07 +0200
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"pmbd"}
  Current user: O.rogoll (id=5)
Completed 500 Internal Server Error in 396ms (ActiveRecord: 183.6ms)

NameError (undefined local variable or method `initialize_tags_filter' for #<IssueQuery:0x0000556027028780>
Did you mean?  initialize_ids_filter
               initialize_author_filter
               initialize_watcher_filter
               initialize_updated_filter
               initialize_created_filter):

plugins/additional_tags/lib/additional_tags/patches/issue_query_patch.rb:24:in `initialize_available_filters_with_tags'
app/models/query.rb:657:in `available_filters'
app/models/query.rb:403:in `build_from_params'
app/models/issue_query.rb:92:in `build_from_params'
plugins/additional_tags/lib/additional_tags/patches/issue_query_patch.rb:43:in `build_from_params_with_tags'
app/helpers/queries_helper.rb:314:in `retrieve_query'
app/controllers/issues_controller.rb:46:in `index'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

```

Cheers
AID-PMBD

**Comment by alexandermeindl** [comment]
For additional_tags version 1.0.1 use cannot use Additionals 3.0.3, too. Use Additionals 3.0.2 for additional_tags 1.0.1

**Comment by AID-PMBD** [comment]
Thank you Alex, with Additionals 3.0.2 it worked!
