### ISSUE TITLE
This tag does not work with redmine-4.2.3-2

### ISSUE THREAD

**Issue by nzugeibeh** [AlphaNodes/additional_tags#19]
Hi,

I have redmine-4.2.3-2 and Ruby 2.6.0.

I installed first additional plug in and then additional_tags. However Redmine won't restart.

I  removed redmindup-tag plug in before installing this plugin.  Also, I dropped tables (taggings, tags) from DB so that  additional_tags creates them when installing it.  and this did not help.
finally, I followed the Readme notes and I added gem 'additional_tags' to gemfile and Redmine started. However, when trying to configure tags it breaks (internal Error)

Could someone assist with this issue?

Thanks,

Nawarz

**Comment by alexandermeindl** [comment]
additional_tags uses its own tables. If taggings and tags exists, it migrate existing tags.

Did you use installation instruction https://github.com/AlphaNodes/additional_tags#installing? With this instruction, both plugins uses stable branch and this should work.
If this did not work for you I need the log entry section with the error message to analyze it.

**Comment by nzugeibeh** [comment]
Thanks Very much for your quick response.

I did followed exact steps (see attached additional_tags.log)
[additional_tags.log](https://github.com/AlphaNodes/additional_tags/files/7837136/additional_tags.log)

Also, I attached Web server logs
[access.log](https://github.com/AlphaNodes/additional_tags/files/7837145/access.log)
[error.log](https://github.com/AlphaNodes/additional_tags/files/7837146/error.log)
.

Note: The error I am getting is both Windows services (redmineThin1 & redmineThin2) are failing to restart

Also, for testing purposes, I have removed all plug-ins except for additional plug in. And I got same issue.
attached: production.log
[production.log](https://github.com/AlphaNodes/additional_tags/files/7837163/production.log)

Thanks again for your help.

Nawarz

**Comment by nzugeibeh** [comment]
Hi Again,

I tired to run redmineThin1 & redmineThin2 in console mode and I got error in attached log file
[ruby_console_mode.log](https://github.com/AlphaNodes/additional_tags/files/7837327/ruby_console_mode.log)

**Comment by alexandermeindl** [comment]
This looks to me, that your application server (thin) cannot find git. Because our plugins support Gemfiles, git have to be installed (this is default with linux).

**Comment by nzugeibeh** [comment]
Hi Alexander,

Thanks for your notice. git is already installed. I used it to clone this plugin.

I believe I found the _root cause_ of this issue on Windows Environment. Redmine's Environment Variables were not set when running services in console mode. Once  I added them to console script, the output was okay and no breaking;

Therefore I added below to Windows System Environment  and both Win services (redmineThin1 & redmineThin2) started without any issues. 

I can use the plug in now ....

set PATH=C:\Bitnami\redmine-4.2.3-2/git\cmd;C:\Bitnami\redmine-4.2.3-2/msys64\mingw32\bin;C:\Bitnami\redmine-4.2.3-2/msys64\mingw64\bin;C:\Bitnami\redmine-4.2.3-2/msys64\usr\bin;C:\Bitnami\redmine-4.2.3-2/sqlite;C:\Bitnami\redmine-4.2.3-2\imagemagick/bin;C:\Bitnami\redmine-4.2.3-2\ruby\bin;C:/Bitnami/redmine-4.2.3-2/php;C:\Bitnami\redmine-4.2.3-2/mariadb\bin;C:\Bitnami\redmine-4.2.3-2/letsencrypt/;C:\Bitnami\redmine-4.2.3-2/common\bin;%PATH%



### **This issue is resolved now.** 

Thanks again for looking into this matter,

**Comment by nzugeibeh** [comment]
Thank you.
