### ISSUE TITLE
Problem upgrading Redmine

### ISSUE THREAD

**Issue by johnbatters** [AlphaNodes/additional_tags#20]
We have upgraded our Redmine version to 4.2.3 from 4.1.1 and this plugin seems to have caused an issue. Redmine doesn't start, but then does start if we remove this plugin.

We've had a look and we can see this error. Can anyone help as we really need this plugin!

![image](https://user-images.githubusercontent.com/453880/151758807-f69bee21-0b4a-4b56-86e1-ee13f0da5609.png)

**Comment by alexandermeindl** [comment]
Hi @johnbatters,

This looks like you already have an table index in your database, which migration tries to update. You can try to drop this index manually and then re-run migration.

**Comment by alexandermeindl** [comment]
No more feedback -> I close this issue.
