### ISSUE TITLE
Tags are deleted when tickets are edited in bulk (redmine edit mode)

### ISSUE THREAD

**Issue by rm-plugin-lurker** [AlphaNodes/additional_tags#22]
Hello,

We are currently using 1.0.0 version of this plugin since ruby version supported is only 2.58 and redmine version is 4.1.1.
So I am not sure if this issue is already fixed.

I checked previous issues reported and found that issue report below is already available in installed version
https://github.com/AlphaNodes/additional_tags/issues/10

**Issue:**
When bulk editing redmine tickets, tags are deleted or modified even if no change should be performed

2 scenarios:
1st scenario
Prerequisite:
1. Ticket A has no tag
2. Ticket B has xxx tag

Procedure
1. Select 2 or more tickets
2. Right-Click > Tags > Add
3. Do not change anything

Result:
Ticket A: xxx tag is added
Ticket B: no change

---
2nd scenario
Prerequisite:
1. Ticket A has yyy tag
2. Ticket B has xxx tag

Procedure
1. Select 2 or more tickets
2. Right-Click > Edit
3. Do not change anything

Result:
Ticket A: yyy tag is deleted
Ticket B: xxx tag is deleted

---

Mostly 2nd scenario is used.
Is it possible to disable editing of Tags on this page? (i.e. remove Tags field)
I attached image.
![image](https://user-images.githubusercontent.com/95681301/165437956-e28500d7-b48b-420a-8b06-c8eebc29fd39.png)

if needed I can update manually in our side, but please do inform which part of code needs to be disabled

**Comment by alexandermeindl** [comment]
Bulk edit should be fixed in latest stable version.

For code changes I cannot offer my help. Please try to study the code by yourself - its open source!

**Comment by rm-plugin-lurker** [comment]
Ok i understand. Thank you for the reply
