### ISSUE TITLE
feature request: Custom colors for tags

### ISSUE THREAD

**Issue by amacado** [AlphaNodes/additional_tags#25]
I was wondering if it would be possible to enhance this great plugin by the option to adjust the colors of the tags by user defined settings?

**Comment by alexandermeindl** [comment]
Hi @amacado 

I see three ways, this would happen:

* you provide a [PR](https://github.com/AlphaNodes/additional_tags/pulls) incl. tests and I'll merge it
* you sponsor this feature. We (https://alphanodes.com/) would develop it, please contact us for a quotation
* you wait. Maybe we develop this feature if some spare time is available. This can take 1-2 year, but there is no actual schedule for it

I would be really nice to have this feature.

**Comment by alexandermeindl** [comment]
Color theme support has been added to change colors.
