### ISSUE TITLE
Add tags for multiple selection

### ISSUE THREAD

**Issue by cristian-spiescu** [AlphaNodes/additional_tags#26]
Hi!

Just like the original "Redmine UP Tags plugin", there is an issue when trying to add a tag for a multiple selection. E.g. I have task1 and task2 as follows:
![image](https://user-images.githubusercontent.com/4469897/178333360-f5f53ffe-a69f-476c-bb2d-61556725ecec.png)

I select the 2 tasks, and I click on "add tag":
![image](https://user-images.githubusercontent.com/4469897/178333636-dda1f8b9-a523-446a-88a8-5ad531494a0a.png)

![image](https://user-images.githubusercontent.com/4469897/178333832-bc90ab5a-fe2f-437d-8794-9314694d35c7.png)

I want to add "tag2" to both tags:
![image](https://user-images.githubusercontent.com/4469897/178334840-3deabfa0-0493-48b9-8e15-c349668fd868.png)

The above dialog behaves actually like "set tags". Not like "add tags". 
* if I add "tag2" in the textbox (so I have tag1, tag2) => both tasks will have tag1, tag2
![image](https://user-images.githubusercontent.com/4469897/178334551-09aa2df0-79ee-443c-90f1-42a5ccf7fb8a.png)

* if I remove tag1 and let only tag2 in the text box => both tasks will have tag2. This will REMOVE tag1 from task1
![image](https://user-images.githubusercontent.com/4469897/178334626-4037b5e5-2f13-4e82-9afa-4d516217df6b.png)

Actually this is the reason why we cannot use this plugin. People may want to bulk add some tags, and they may end in corrupting the tasks.

Thanks in advance!
Cristian

**Comment by cristian-spiescu** [comment]
I find it interesting that this issue wasn't discovered until now, and that it seems not to bother people. Anyway, for us, it's a showstopper. We'll try to fix it and propose a PR. I hope the repo policy is to review and try to merge PRs from users external to the project. It's a bit challenging because we are not Ruby devs, but let's see what we manage to do.

**Comment by Theodorson** [comment]
Hi,

I am colleague with @cristian-spiescu and I made a fix for this issue. This is the PR for fixing issue https://github.com/AlphaNodes/additional_tags/pull/27

**Comment by Theodorson** [comment]
Hi,

I fixed the tests. Now I think the PR can be merged. Can you please approve to retry the build ?

**Comment by Theodorson** [comment]
Hi, 
I fixed linter too. I didn't modified with nothing the places with problems, I don't know how it passed in the past, anyway, now I think is fine. Can you please approve to run the build again ?

**Comment by Theodorson** [comment]
Hi,
Was one more problem with a slim file. Can you please approve to run the build again ?

**Comment by Theodorson** [comment]
Hi,
Could you please approve to trigger another build ?

**Comment by alexandermeindl** [comment]
This is fixed with #39
