### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Interfud** [AlphaNodes/additional_tags#28]
After the update
Error when copying a task
Redmine version                5.0.1.stable
  Ruby version                   3.1.2-p20 (2022-04-12) [x86_64-linux]
  Rails version                  6.1.6

[4b70ab9c-e250-47e3-b379-e0a115d52e35] plugins/additional_tags/lib/additional_tags/patches/issue_patch.rb:77:in `copy_from_with_tags'
[4b70ab9c-e250-47e3-b379-e0a115d52e35] plugins/issue_recurring/lib/issue_recurring/issue_patch.rb:5:in `copy_from'

**Comment by Interfud** [comment]
a nonexistent method is called!!!
77           copy_from_without_tags arg, **options

**Comment by alexandermeindl** [comment]
Hi @Interfud,

I cannot confirm this problem with the latest version of additional_tags. Which version do you use? Do you use other plugins? If yes, you should try to isolate the problem with removing other plugins.

**Comment by Interfud** [comment]
Broke after the update

**Comment by Interfud** [comment]
Broke the plugin https://github.com/cryptogopher/issue_recurring

**Comment by alexandermeindl** [comment]
Read this: https://github.com/AlphaNodes/additional_tags/issues/9#issuecomment-778642718 - additional_tags is using alias_method, this is not compatible with [issue_recurring](https://github.com/cryptogopher/issue_recurring). additional_tags did not change anything about this, I suppose you add issue_recurring plugin or issue_recurring switched to prepend. Remove issue_recurring and it should work, again.

**Comment by Interfud** [comment]
Thanks. Deleted everything works.

**Comment by cryptogopher** [comment]
For reference, there is a patch for https://github.com/cryptogopher/issue_recurring which allows it to be run with plugins using `alias_method`.

You just need to replace 1 file in your plugin directory with this one: https://github.com/cryptogopher/issue_recurring/blob/issue30/lib/issue_recurring/issue_patch.rb

It probably won't be actively updated and is a temporary workaround until other plugins will finaly upgrade to using `prepend + super`.
