### ISSUE TITLE
Additionnal tags with Redmine 5.0.0

### ISSUE THREAD

**Issue by blessleness** [AlphaNodes/additional_tags#29]
Hi

We just upgraded our server as follows :
Environment:
  Redmine version                5.0.0.stable
  Ruby version                   2.6.10-p210 (2022-04-12) [x86_64-linux]
  Rails version                  6.1.4.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Redminex_theme
SCM:
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  000_redmine_x_ux_upgrade       1.3.0
  redmine_lightbox               1.0.1
  redmine_x_assets               2.1.1
  redmine_x_resources            2.1.2
  view_customize                 3.0.0

Before that we had Redmine 4.x without RedmineX and we used to have Additionnal plugin runinng.
Now it seems that the current version is no longer compatible with Ruby 2.6.

Is there any older version that would be still available for us? If yes how can I get it?

Thanks a lot for your kind answer

**Comment by alexandermeindl** [comment]
Hi @blessleness ,

see https://github.com/AlphaNodes/additional_tags#requirements for requirements: Ruby 2.7 is required for latest additional_tags version. You find all older version here: https://github.com/AlphaNodes/additional_tags/tags

**Comment by blessleness** [comment]
Hi Alexander,

Thanks for your fast reply. Can you confirm that older version are compatible with ruby 2.6 ? I cannot find the compatibility… sorry I’m not very used to Git

Thanks

***@***.***<https://cloud.letsignit.com/collect/bc/5f575952dce7850008fa878d?p=oXsx49iRCxIwYm26MLY74U3C_utT9SYthg_KusTHvi_4j59PK2UF5tECG8V8cX2u66jkycLhCvBfYfs3xfZxM9M9nm9OO3aLL3a6XeNu84qPa11Ozq3efyKqEkcBBhBdUMB3AbD40iLsI9dyJrnCtbo8saBdXx_f9kqyW3eMwXhT_S9zgm37oomNyRLbTVZI>
Maxime BLASS
Directeur Ingénierie Applicative France
Service Client
7/7j - 9h/12h → 13h/17h
***@***.******@***.***>
***@***.***

Boutique<https://cloud.letsignit.com/collect/bc/5f575952dce7850008fa878d?p=oXsx49iRCxIwYm26MLY74U3C_utT9SYthg_KusTHvi_4j59PK2UF5tECG8V8cX2u66jkycLhCvBfYfs3xfZxM9M9nm9OO3aLL3a6XeNu84rgW2ccorhSS3Bghc7Tg0H2IjuX4Pz30lWpWSWgBbEuJ9ZDAys7guxXtSyRjtChFlcUE05j1IyRmolZ0OhSj4j8> I Blog<https://cloud.letsignit.com/collect/bc/5f575952dce7850008fa878d?p=oXsx49iRCxIwYm26MLY74U3C_utT9SYthg_KusTHvi_4j59PK2UF5tECG8V8cX2u66jkycLhCvBfYfs3xfZxM9M9nm9OO3aLL3a6XeNu84pXKZsb4xtkHCWJr0WSN7p2FgjzjOoJaw82AXdubEYT96C8KtiOJfqOReQmFoGUxKahjq7SvNO3vJLo4_7RYCje>
***@***.***<https://cloud.letsignit.com/collect/bc/5f575952dce7850008fa878d?p=oXsx49iRCxIwYm26MLY74U3C_utT9SYthg_KusTHvi_4j59PK2UF5tECG8V8cX2u66jkycLhCvBfYfs3xfZxM9M9nm9OO3aLL3a6XeNu84oVdtAfwbZCl5kBv6UkIBwLByf4kPF0Zps4UxxTMIY-9HtQ3-KkCK9Phg0CTaLhl2uwpKMJuB_rvSpmbXSF_nzzn0FXNpYiHuJyfY760wv09KhA8fSF2EWwNO7eiyX5nvI=>
***@***.***<https://cloud.letsignit.com/collect/bc/5f575952dce7850008fa878d?p=oXsx49iRCxIwYm26MLY74U3C_utT9SYthg_KusTHvi_4j59PK2UF5tECG8V8cX2u66jkycLhCvBfYfs3xfZxM9M9nm9OO3aLL3a6XeNu84oWcah92IptFgI3Bl3AAQj-JiU5mY-7ZoyCRMdFzch_ZTZNWCr2aDkbMzVioPGiE4pUB-zpwjSP9Z_VrOKzUBybGPQcvBwwSRq6M2KrCjraYA==>
***@***.***<https://cloud.letsignit.com/collect/bc/5f575952dce7850008fa878d?p=oXsx49iRCxIwYm26MLY74U3C_utT9SYthg_KusTHvi_4j59PK2UF5tECG8V8cX2u66jkycLhCvBfYfs3xfZxM9M9nm9OO3aLL3a6XeNu84rSp3FySnPQixaefKedCTtm9YVyeZxJNgSO-0rbUnVvraEgZEtwgFEpC01CAtpnr83-SosdJA3ztH2kkVF-UQ86w7gMpYHGLUnhlJusaT6wRQ==>



De : Alexander Meindl ***@***.***>
Envoyé : mercredi 28 septembre 2022 16:01
À : AlphaNodes/additional_tags ***@***.***>
Cc : Maxime BLASS ***@***.***>; Mention ***@***.***>
Objet : Re: [AlphaNodes/additional_tags] Additionnal tags with Redmine 5.0.0 (Issue #29)


Hi @blessleness<https://github.com/blessleness> ,

see https://github.com/AlphaNodes/additional_tags#requirements for requirements: Ruby 2.7 is required for latest additional_tags version. You find all older version here: https://github.com/AlphaNodes/additional_tags/tags

**Comment by alexandermeindl** [comment]
Hi,

do see the requirements for your choosen version, click on your version https://github.com/AlphaNodes/additional_tags/tags and scroll down to see requirements. Older versions support older ruby versions, but I do not recommend to use it because other bugs are fixed in latest version (especially for Redmine 5).

**Comment by alexandermeindl** [comment]
Hi @blessleness,

did you solve it? Can we close this issue?

**Comment by blessleness** [comment]
Not yet, but you can close the ticket, I don't know when my IT is going to work on that.

Thanks for your reply
________________________________
De : Alexander Meindl ***@***.***>
Envoyé : vendredi 14 octobre 2022 17:13
À : AlphaNodes/additional_tags ***@***.***>
Cc : Maxime BLASS ***@***.***>; Mention ***@***.***>
Objet : Re: [AlphaNodes/additional_tags] Additionnal tags with Redmine 5.0.0 (Issue #29)


Hi @blessleness<https://github.com/blessleness>,

did you solve it? Can we close this issue?

**Comment by alexandermeindl** [comment]
@blessleness any news? Can we close this issue?

**Comment by blessleness** [comment]
Yes you can close.

Thx

Envoyé depuis mon mobile

Le 19 déc. 2022 02:08, Alexander Meindl ***@***.***> a écrit :

@blessleness<https://github.com/blessleness> any news? Can we close this issue?
