### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by mgcd-jed** [alphanodes/additional_tags#38]
The README says that we can use different color themes, but I do not see this  :
![image](https://user-images.githubusercontent.com/108806857/204253798-f19d8967-6f59-45aa-8769-189317da5ff7.png)

And having color schemes is not enough, the best option would be to allow for choosing the color of each tag individually (or as part as a theme).

**Comment by ClaudiaMeindl** [comment]
@mgcd-jed 
thank you for your message. The color scheme chooser is only available via main branch.
