### ISSUE TITLE
Bug: when editing a custom query, only one of the saved filter is visible

### ISSUE THREAD

**Issue by athanasio** [AlphaNodes/additional_tags#7]
I have a series of custom queries, which they work before and after installing the plugin, if I don't edit them.

If I edit the query before I install the plugin, I can see all filters used to construct the query. This is the expected behaviour.

If I install the plugin, editing a query shows only the first filter used. If I save the query at this stage I am losing all the additional filters used. If I add them again manually before saving the query, it is working as expected, but this is not ideal and it is prone to errors.

I went through the ruby code (sadly I'm not an expert) but I couldn't figure out the problem.

**Comment by alexandermeindl** [comment]
Hi @athanasio 
thanks for reporting this!
Can you provide me more information to debug this?
- did you use another plugin for tagging before? redmine_tags or redmineup_tags? 
- if yes, can you check, if exiting queries exists, which do not include tag filters?

**Comment by athanasio** [comment]
Hello @alexandermeindl , thanks for replying! I didn't install any of the other tag plugins. I also want to mention that by simply removing the plugin from `plugins/` and restarting Redmine solves the problem.

**Comment by alexandermeindl** [comment]
Hi @athanasio 

thanks, this information helps debugging. I'll take a look at it.

**Comment by alexandermeindl** [comment]
Hi @athanasio 

I can confirm this bug, I reproduced on my test installation.  I fixed it with https://github.com/AlphaNodes/additionals/commit/5fedf5b7f38225dfc2bac3e9f22b0125352fe43d. You need the latest update of the [additionals plugin](https://github.com/AlphaNodes/additionals) (Master branch) to get the fix. There was no change required for additional_tags plugin.
